services:
  ttyd:
    container_name: ttyd
    build: ./ttyd
    image: ttyd
    command: ttyd --writable bash
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  collector:
    container_name: collector
    build: ./collector
    image: collector
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - ./captures:/captures
      - /var/run/docker.sock:/var/run/docker.sock:ro
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    command: /opt/collector/run.sh
    
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017