services:
  asterisk:
    container_name: asterisk
    build: ./asterisk
    image: asterisk
    command: asterisk -f -vv
    tty: true
    network_mode: "host"
    environment:
      EXTERNAL_IP: 192.168.1.50
      LOCAL_NET: 192.168.1.0/24
    volumes:
      - ./asterisk/config:/etc/asterisk     

  sippts:
    container_name: sippts
    build: ./sippts
    image: sippts
    tty: true
    volumes:
      - ./audio.wav:/audio.wav        # audio per rtp_inject

  wireshark:
    container_name: wireshark
    build: ./wireshark
    image: wireshark
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix  
    network_mode: "host"            
    privileged: true