services:
  freeswitch:
    container_name: freeswitch
    build: ./freeswitch
    image: freeswitch
    network_mode: "host"
    mem_limit: 1g # per simulare l'attacco DoS
  
  attacker:
    container_name: attacker
    build: ./attacker
    image: attacker
    tty: true
    volumes:
      - ./attacker/spoofing.py:/spoofing.py
      - ./attacker/dos-sipflood.py:/dos-sipflood.py