services:
  node_firefox:
    container_name: node_firefox
    build: ./node_firefox
    image: node_firefox
    tty: true
    ports:
    - 80:80

  gophish:
    container_name: gophish
    build: ./gophish
    image: gophish
    tty: true
    network_mode: "host"
    volumes:
      - ./gophish/data/gophish.db:/opt/gophish/gophish.db

  firefox:
    container_name: firefox
    build: ./firefox
    image: firefox
    tty: true
    network_mode: "host"
    environment:
    - DISPLAY=${DISPLAY}
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native