services:
  vdoninja:
    container_name: vdoninja
    build: ./vdoninja
    image: vdoninja
    network_mode: "host"

  node_mongoose:
    container_name: node_mongoose
    build: ./node_mongoose
    image: node_mongoose
    tty: true
    network_mode: "host"
    restart: always