services:
  coturn:
    container_name: coturn
    build: ./coturn
    image: coturn
    network_mode: "host"
    command: turnserver -v --user=username1:password1

  stunner:
    container_name: stunner
    build: ./stunner
    image: stunner
    tty: true
    network_mode: "host"
    command: > 
      stunner socks 
      --turnserver 192.168.1.50:3478 
      --protocol tcp 
      --username username1 
      --password password1 
      --listen 0.0.0.0:9999